import { useMemo, useState } from 'react';

type Lead = { name: string; company: string; source: string; value: string; status: string; score: number };
const leads: Lead[] = [
  { name: 'Arjun Reddy', company: 'UrbanNest', source: 'Meta Ads', value: '₹4.8L', status: 'Hot', score: 96 },
  { name: 'Sneha Rao', company: 'PropEdge', source: 'Website', value: '₹3.2L', status: 'Qualified', score: 88 },
  { name: 'Rahul Mehta', company: 'Skyline Realty', source: 'WhatsApp', value: '₹2.4L', status: 'Contacted', score: 76 },
  { name: 'Priya Sharma', company: 'HomeSquare', source: 'Google Ads', value: '₹5.1L', status: 'Hot', score: 94 },
  { name: 'Vikram Singh', company: 'Brick & Beam', source: 'Referral', value: '₹1.9L', status: 'New', score: 61 },
];
const nav = ['Overview', 'Leads', 'Pipeline', 'AI Calls', 'Analytics'];
export default function App() {
  const [active, setActive] = useState('Overview'); const [query, setQuery] = useState('');
  const filtered = useMemo(() => leads.filter(l => `${l.name} ${l.company}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark">AI</div><div><strong>LeadFlow</strong><span>AI CRM</span></div></div><div className="workspace"><span className="avatar">AK</span><div><b>Abhiram's Workspace</b><small>Growth team</small></div></div><nav>{nav.map(item => <button key={item} className={active === item ? 'active' : ''} onClick={() => setActive(item)}><span>◈</span>{item}</button>)}</nav><div className="sidebar-bottom"><button>⚙ Settings</button><button>↪ Sign out</button></div></aside>
  <main><header className="topbar"><div><p className="crumb">Workspace / {active}</p><h1>{active}</h1></div><div className="top-actions"><button className="icon">⌕</button><button className="icon">♧</button><div className="user-avatar">AK</div></div></header>
  <section className="welcome"><div><p className="eyebrow">MONDAY, AUGUST 10</p><h2>Good evening, Abhiram 👋</h2><p>Here's what's happening with your sales pipeline today.</p></div><button className="primary">＋ Add lead</button></section>
  <section className="stat-grid">{[['Total leads','1,284','+18.2%'],['Hot leads','214','+12.4%'],['AI calls today','86','+24.1%'],['Pipeline value','₹28.6L','+8.7%']].map(([a,b,c]) => <article className="stat" key={a}><span>{a}</span><strong>{b}</strong><p>↑ {c} <small>vs last month</small></p></article>)}</section>
  <section className="main-grid"><article className="card"><div className="card-head"><div><h3>Recent leads</h3><p>Latest prospects entering your pipeline</p></div><button className="link">View all →</button></div><div className="table-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search leads..."/><button>Filter</button></div><div className="table-wrap"><table><thead><tr><th>Lead</th><th>Source</th><th>Value</th><th>Score</th><th>Status</th></tr></thead><tbody>{filtered.map(l=><tr key={l.name}><td><div className="lead-name"><span className="person">{l.name.split(' ').map(x=>x[0]).join('')}</span><div><b>{l.name}</b><small>{l.company}</small></div></div></td><td>{l.source}</td><td><b>{l.value}</b></td><td><span className="score">{l.score}</span></td><td><span className={`badge ${l.status.toLowerCase()}`}>{l.status}</span></td></tr>)}</tbody></table></div></article>
  <article className="card"><div className="card-head"><div><h3>AI activity</h3><p>Automation running in real time</p></div><span className="live"><i/> LIVE</span></div>{[['☎','AI completed 42 follow-up calls','8 min ago'],['✦','11 leads marked as hot','21 min ago'],['↗','3 proposals sent automatically','38 min ago'],['◎','2 callbacks scheduled','1 hr ago']].map(x=><div className="activity-row" key={x[1]}><span className="activity-icon">{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}<div className="ai-summary"><span>AI automation efficiency</span><b>92%</b><div className="progress"><i style={{width:'92%'}}/></div></div></article></section>
  <section className="bottom-grid"><article className="card chart"><div className="card-head"><div><h3>Lead performance</h3><p>Qualified leads over the last 7 days</p></div><select><option>Last 7 days</option></select></div><div className="fake-chart"><div className="chart-grid"/><svg viewBox="0 0 600 180" preserveAspectRatio="none"><path d="M0 145 C65 135 72 100 135 112 S200 132 260 92 S320 122 365 72 S435 88 480 55 S540 72 600 28" fill="none" stroke="currentColor" strokeWidth="4"/><path d="M0 145 C65 135 72 100 135 112 S200 132 260 92 S320 122 365 72 S435 88 480 55 S540 72 600 28 L600 180 L0 180Z" fill="currentColor" opacity=".08"/></svg></div></article><article className="card"><div className="card-head"><div><h3>Pipeline</h3><p>Lead distribution by stage</p></div></div>{[['New',312],['Contacted',244],['Qualified',168],['Proposal',91],['Closed',39]].map(([n,c])=><div className="pipe" key={String(n)}><div><span>{n}</span><b>{c}</b></div><div className="pipe-track"><i style={{width:`${Number(c)/3.12}%`}}/></div></div>)}</article></section><footer>LeadFlow AI CRM · Built for smarter sales teams</footer></main></div>;
}
